### ISSUE TITLE
Please Update to Grafana 7.3.3

### ISSUE THREAD

**Issue by kakamband** [ericmend/heroku-grafana#1]
Hi Eric,
Please Update to Grafana 7.3.3 & install "WordPress plugin dashboard" as pre-installed plugins
waiting for your response
finest regards

**Comment by ericmend** [comment]
I don't know this plugin "WordPress plugin dashboard". At least, there is nothing listed on the official page: https://grafana.com/grafana/plugins

**Comment by ericmend** [comment]
updated to version 7.4.3
